name: Floristics
main: land.jay.floristics.Floristics
version: 2.2
api-version: 1.14
softdepend: [GriefPrevention, WorldGuard, RedProtect]
commands:
    floristics:
        aliases: flo
        description: enable or disable growth in GriefPrevention claims
        usage: /floristics ...
