name: Floristics
main: land.jay.floristics.Floristics
version: 2.6
api-version: 1.17
softdepend: [Towny]
commands:
    floristics:
        aliases: flo
        description: Manage floristics and toggle growth in regions.
        usage: /floristics ...
